### ISSUE TITLE
error with commands 

### ISSUE THREAD

**Issue by thatonedudeverygeneric** [ghaku/nekos.life-discord-bot#13]
i might just be stupid, but whenever I try to send a command in a channel the bot doesn't send anything and i get this error message
![image](https://user-images.githubusercontent.com/104653241/166104775-b3be11ed-2a1f-4087-b503-3553ce53faa2.png)

**Comment by arktn** [comment]
It's an error with an unhandled promise, it's probably because the code is outdated. I will try to update it this weekend.
