### ISSUE TITLE
this error when attempting to start

### ISSUE THREAD

**Issue by xSkyyy** [ghaku/nekos.life-discord-bot#5]
`0 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 's' ]
1 info using npm@7.5.4
2 info using node@v14.16.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/root/bot/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session de86271b8aa9dd9e
20 timing npm:load Completed in 17ms
21 timing command:search Completed in 1ms
22 verbose stack Error: search must be called with arguments
22 verbose stack     at search (/usr/local/lib/node_modules/npm/lib/search.js:29:11)
22 verbose stack     at cmd (/usr/local/lib/node_modules/npm/lib/search.js:18:27)
22 verbose stack     at Object.[_runCmd] (/usr/local/lib/node_modules/npm/lib/npm.js:119:7)
22 verbose stack     at fn (/usr/local/lib/node_modules/npm/lib/npm.js:46:40)
22 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cli.js:58:7)
23 verbose cwd /root/bot
24 verbose Linux 4.15.0-126-generic
25 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "s"
26 verbose node v14.16.1
27 verbose npm  v7.5.4
28 error search must be called with arguments
29 verbose exit 1`

**Comment by xSkyyy** [comment]
![image](https://user-images.githubusercontent.com/58812660/115096194-02cfb700-9f1c-11eb-93e1-75cbb52f8f58.png)

**Comment by arktn** [comment]
You have do give node some more arguments on what to start.
