### ISSUE TITLE
wut is this

### ISSUE THREAD

**Issue by HipotalamuS0** [ghaku/nekos.life-discord-bot#7]
idk help plz

**Comment by HipotalamuS0** [comment]
![image](https://user-images.githubusercontent.com/57671808/131237480-c3fc987f-553c-40cf-8354-01d7f900bb35.png)

**Comment by arktn** [comment]
Try installing the nekos.life module by using "npm i nekos.life" in the directory.

**Comment by HipotalamuS0** [comment]
Is there any way I can keep the bot running 24/7? What you said worked and the bot works great!

**Comment by HipotalamuS0** [comment]
and i have no money actually :(

**Comment by arktn** [comment]
If you want to host the bot for free you can either use [Glitch](https://www.glitch.com), [Heroku](https://www.heroku.com/) or both. If you need help on that there are tons of tutorials out there, that show you in very simple ways how to host your bot on either one of these free sites.

**Comment by HipotalamuS0** [comment]
im using repl.it but these apps are safe?

**Comment by arktn** [comment]
All of these apps are deemed save, as far as I know.

**Comment by HipotalamuS0** [comment]
thanks for help!  dude you are doing great job!
